### ISSUE TITLE
Card links accept CTRL+Click to open in new window?

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#553] opened 2020-10-05 14:30 UTC
# Problem 

The faux card button does not allow for links to be opened in a new window. 

<img width="533" alt="Screen Shot 2020-10-05 at 9 31 51 AM" src="https://user-images.githubusercontent.com/1036433/95092897-c2ca8480-06ed-11eb-8dd0-606904a15c95.png">

# Proposed Solution

Adjust `card.js` to allow faux button to open faux link in a new window.

**Comment by pyrello** [comment] 2021-05-15 14:10
Detecting control key event: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/ctrlKey

**Comment by pyrello** [comment] 2021-05-17 21:24
I don't believe that this is possible without creating and maintaining our own custom context menu. I don't think we should do that, but in case we decide to, here is an article describing how: https://www.sitepoint.com/building-custom-right-click-context-menu-javascript/

The issue is that there is just no way to add items to the existing browser context menu.

**Comment by pyrello** [comment] 2021-05-18 16:00
I'm closing this as won't fix because I don't think the path forward for resolving this is reasonable.

**Closed by pyrello** 2021-05-18 16:00 UTC
Labels: a11y, wontfix
